from flask import Flask, redirect, url_for, request, Response
import asyncio

app = Flask(__name__) 

async def background_task(swipe_respone):
    await asyncio.sleep(5)
    print("Gotti ", swipe_respone)

@app.route("/") 
def index(): 
    return """<html>
<body>

<h1>Growing scale-free networks with tunable clustering.</h1>
<h2>Authors Petter Holme, Beom Jun Kim</h2>
<p>We extend the standard scale-free network model to include a “triad formation step.” We analyze the geometric properties of networks generated by this algorithm both analytically and by numerical calculations, and find that our model possesses the same characteristics as the standard scale-free networks such as the power-law degree distribution and the small average geodesic length, but with the high clustering at the same time. In our model, the clustering coefficient is also shown to be tunable simply by changing a control parameter—the average number of triad formation trials per time step.</p>

</body>
</html>"""

@app.route('/swipe', methods = ['POST'])
async def swipe():
    if request.method == 'POST':
        swipe_respone = request.form['swipeResponse']
        asyncio.ensure_future(background_task(swipe_respone))
        return redirect(url_for('index'))
    else:
        return Response("Only post endpoint here", status=400)
  
if __name__ == "__main__": 
    app.run(debug=True) 